### ISSUE TITLE
Improve/extend CLI prompt tools

### ISSUE THREAD

**Issue by rpreen** [AI-SDC/SACRO-ML#294]
As of `1.2.0` the CLI prompt tools were added: 
* `$ sacroml gen-attack` tool that produces the attack config  `attack.yaml` for running attacks on the CLI
* `$ sacroml gen-target` tool that produces the directory `target_dir/` that contains a `target.yaml` and model/data files for running attacks on the CLI
* subsequently running `$ sacroml run target_dir/ attack.yaml` executes the attacks and generates a report

These tools need to be improved and extended to provide a better user experience, such as more graceful exiting, and support for different scenarios when the model was not trained in Python, and where the data may be large and not able to be copied and also to handle various preprocessing situations. It seems likely that the `sacroml/attacks/target.py` will also need to be modified and an `sacroml/attacks/model.py` may need to be created to wrap target models to encapsulate non-scikit-learn models with `fit()`, `predict()` etc. functions that the attacks can assume exists.

**Comment by rpreen** [comment]
At the moment, when you `sacroml run` with a given target folder and attack config, it tries to load the saved model and data files from the target folder into a `Target` object with `load()` in target.py. If everything is loaded in the `Target` object everything can run as normal.

https://github.com/AI-SDC/SACRO-ML/blob/c7d3ec39a0ae1d092b5386d9aab03cd1bb025b48/sacroml/attacks/target.py#L350-L389

If a `model_path` is specified in the target.yaml (in the target folder) it will try to load the model, but it only supports scikit-learn models currently and will throw an exception if it's not a pkl model. 

The worst case attack checks if there is a loaded model and training data available and then generates the probabilities as usual; if that's not available, then it checks if the predicted probabilities are available and uses those (as in user story 4). 

https://github.com/AI-SDC/SACRO-ML/blob/c7d3ec39a0ae1d092b5386d9aab03cd1bb025b48/sacroml/attacks/worst_case_attack.py#L116-L134

**TODO:** 

- [x] Update target.py so that the train/test probabilities can be loaded from the target.yaml.
- [ ] Update target.py to support loading models other than just *.pkl.
- [x] Add better handling of unsupported models to the attack modules.
- [x] Copy unsupported models to the target directory
- [x] Deal with situations where the datasets are large (currently they get copied to the target dir)
- [x] Deal with complex preprocessing scenarios

**Comment by rpreen** [comment]
CSV files are currently assumed to not have header rows because of the following line - I don't think there is a nice way to check whether there is one or not and it seems a safer assumption that there wont be one. This might need to be made more clear to users.

https://github.com/AI-SDC/SACRO-ML/blob/3396c94677ffea6bc7eadd6e690318aaa9cd7e41/sacroml/attacks/target.py#L456

**Comment by rpreen** [comment]
There is this really nice Python library for CLI prompting: [prompt-toolkit](https://github.com/prompt-toolkit/python-prompt-toolkit) which includes the ability to do autocompletion, styling, etc.

In #330 I have added this tool to the dependencies and included it for the path completion, etc. in the `gen-target` and `gen-attack` prompts.

We could modify the `sacroml/main.py` to use the prompt-toolkit so that when the user types `$ sacroml` on the console, it starts an interactive prompt which will then have a help and be more user friendly; and then for example, they can type `run target_dir/ attack.yaml` or `gen-attack`, etc.

**Comment by jim-smith** [comment]
@rpreen is this till open?

**Comment by rpreen** [comment]
There have been a bunch of updates to them. But they probably could be further improved - it needs more testing/playing and feedback. It may need some updates to make it clearer for the scenario where it's an unsupported model (e.g., from R) but the probas are supplied as csv.
